# Generated by Django 4.2.8 on 2023-12-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipehome',
            name='recipeimg',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
