# Generated by Django 4.2.8 on 2023-12-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exam',
        ),
    ]
